# Generated by Django 4.2 on 2023-04-28 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Segmentation',
            fields=[
                ('patient_id', models.BigAutoField(default=0, primary_key=True, serialize=False)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='segmentation.type')),
            ],
        ),
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField(default=0)),
                ('y', models.IntegerField(default=0)),
                ('width', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('segmentation', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='segmentation.segmentation')),
            ],
        ),
    ]
