# Generated by Django 4.2 on 2023-04-28 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segmentation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='segmentation',
            name='type_test',
            field=models.CharField(choices=[('1', 'ONE'), ('2', 'TWO'), ('3', 'THREE')], default='', max_length=20),
        ),
    ]
